### PR TITLE
ARD: Fix für Untertitel-URLs

### LINKED ISSUE #365: [Bug] Fehlerhafte Untertitellinks bei Sendungen der ARD
Betreff:
1. [Weissensee Folge 19/20 UT link kaputt](https://forum.mediathekview.de/topic/1394/weissensee-folge-19-20-ut-link-kaputt)
2. [Untertitel zu Weissensee (github)](https://github.com/mediathekview/MediathekView/issues/316)
3. [Fehlerhafte Untertitellinks bei Sendungen der ARD (MVForum)](https://forum.mediathekview.de/topic/1400/fehlerhafte-untertitellinks-bei-sendungen-der-ard)

Der Fehlerteufel scheint eingeschlichen zu sein, denn seit einiger Zeit wird die Untertitel-Datei einer jeweiligen ARD-Sendung fehlerhaft in der MV-Filmliste protokolliert.  Wie im Betr. 1 erst gemeldet wurde, scheint es so aus:

**_h-ttp://www.ardmediathek.de_** h-ttps//www.ardmediathek.de/subtitle/230645

Hier ist eine Abbildung des jetzigen Standes, wobei 4404 von 5981 ARD-Sendungen mit Untertitlung den Fehler aufweisen:

ardsubtitleproblem

Bei meiner Stichprobe funzt die https-URL.

### PR DESCRIPTION
**Pull request by pidoubleyou**
Fixes #365

### CODE REVIEW

File: src/main/java/mServer/crawler/sender/MediathekArd.java [hunk 1]
```diff
@@ -189,7 +190,7 @@ private String determineHdFromNormal(final String urlNormal) {
     }
 
     private void filmSuchen_old(final String urlSendung, final String thema, final String titel,
```
Comment (alex1702) [inline src/main/java/mServer/crawler/sender/MediathekArd.java]: MINOR Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00100)

File: src/main/java/mServer/crawler/sender/MediathekArd.java [hunk 2]
```diff
@@ -304,11 +305,11 @@ private void filmSuchen1(final String strUrlFeed, final String thema, final bool
     }
 
     private void filmSuchen2(final String urlFilm_, final String thema, final String titel,
```
Comment (alex1702) [inline src/main/java/mServer/crawler/sender/MediathekArd.java]: CRITICAL Refactor this method to reduce its Cognitive Complexity from 38 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)

File: src/main/java/mServer/crawler/sender/MediathekArd.java [hunk 3]
```diff
@@ -474,19 +474,18 @@ public MediathekArd(final FilmeSuchen ssearch, final int startPrio) {
...
     listeThemen.clear();
     MSStringBuilder seite = new MSStringBuilder(Const.STRING_BUFFER_START_BUFFER);
     meldungStart();
     final GetUrl getUrlIo = new GetUrl(getWartenSeiteLaden());
     seite = getUrlIo.getUri(SENDERNAME, ADRESSE_THEMA, StandardCharsets.UTF_8, 5 /* versuche */,
-        seite, "" /* Meldung */);
+            seite, "" /* Meldung */);
     if (seite.length() == 0) {
       Log.sysLog("ARD: Versuch 2");
       warten(2 * 60 /* Sekunden */);
```
Comment (alex1702) [inline src/main/java/mServer/crawler/sender/MediathekArd.java]: MINOR Cast one of the operands of this multiplication operation to a "long". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2184)

File: src/main/java/mServer/crawler/sender/MediathekArd.java [hunk 4]
```diff
@@ -276,7 +277,7 @@ private void filmSuchen1(final String strUrlFeed, final String thema, final bool
         filmSuchen2(url, thema, titel, d, datum, zeit, urlSendung);
       }
       if (!Config.getStop() && weiter
-          && (CrawlerTool.loadLongMax() || thema.equalsIgnoreCase("alpha-Centauri"))) {
+              && (CrawlerTool.loadLongMax() || thema.equalsIgnoreCase("alpha-Centauri"))) {
```
Comment (alex1702) [inline src/main/java/mServer/crawler/sender/MediathekArd.java]: CRITICAL Use already-defined constant 'THEMA_ALPHA_CENTAURI' instead of duplicating its value here. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)

File: src/main/java/mServer/crawler/sender/MediathekArd.java [hunk 5]
```diff
@@ -235,7 +236,7 @@ private void filmSuchen1(final String strUrlFeed, final String thema, final bool
       while (!Config.getStop() && (pos = seite1.indexOf(MUSTER_FILM_SUCHEN1, pos)) != -1) {
```
Comment (alex1702) [inline src/main/java/mServer/crawler/sender/MediathekArd.java]: MINOR Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS135)

File: src/main/java/mServer/crawler/sender/MediathekArd.java [hunk 6]
```diff
@@ -105,7 +106,7 @@ private void addTage() {
               thema = thema.substring(0, thema.indexOf(','));
             }
             datum = seite1
-                .extract("<title>Videos (TV-Sendungen) des Senders Das Erste vom", "- ARD").trim();
+                    .extract("<title>Videos (TV-Sendungen) des Senders Das Erste vom", "- ARD").trim();
             titel = seite1.extract("<h4 class=\"headline\">", "<", pos);
```
Comment (alex1702) [inline src/main/java/mServer/crawler/sender/MediathekArd.java]: CRITICAL Define a constant instead of duplicating this literal "<h4 class=\"headline\">" 3 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)

File: src/main/java/mServer/crawler/sender/MediathekArd.java [hunk 7]
```diff
@@ -105,7 +106,7 @@ private void addTage() {
...
             dauer = seite1.extract("<p class=\"subtitle\">", "<", pos);
```
Comment (alex1702) [inline src/main/java/mServer/crawler/sender/MediathekArd.java]: CRITICAL Define a constant instead of duplicating this literal "<p class=\"subtitle\">" 3 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)

File: src/main/java/mServer/crawler/sender/MediathekArd.java [hunk 8]
```diff
@@ -379,8 +380,8 @@ private void filmSuchen2(final String urlFilm_, final String thema, final String
         }
         String subtitle = seite2.extract("subtitleUrl\":\"", "\"");
         if (!subtitle.isEmpty()) {
-          if (!subtitle.startsWith("http://www.ardmediathek.de")) {
-            subtitle = "http://www.ardmediathek.de" + subtitle;
+          if (!subtitle.startsWith("http")) {
```
Comment (alex1702) [inline src/main/java/mServer/crawler/sender/MediathekArd.java]: MAJOR Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1066)

**Comment by alex1702** [comment]
SonarQube analysis reported 46 issues
* ![CRITICAL][CRITICAL] 12 critical
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 27 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [MediathekArd.java#L77](https://github.com/mediathekview/MServer/blob/a1ecc3f1730f73844173ee73e4a1666e1f02d479/src/main/java/mServer/crawler/sender/MediathekArd.java#L77): Refactor this method to reduce its Cognitive Complexity from 35 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![CRITICAL][CRITICAL] [MediathekArd.java#L87](https://github.com/mediathekview/MServer/blob/a1ecc3f1730f73844173ee73e4a1666e1f02d479/src/main/java/mServer/crawler/sender/MediathekArd.java#L87): Define a constant instead of duplicating this literal "Leere Seite: " 6 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [MediathekArd.java#L94](https://github.com/mediathekview/MServer/blob/a1ecc3f1730f73844173ee73e4a1666e1f02d479/src/main/java/mServer/crawler/sender/MediathekArd.java#L94): Use already-defined constant 'MUSTER_ADD_TAGE' instead of duplicating its value here. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [MediathekArd.java#L102](https://github.com/mediathekview/MServer/blob/a1ecc3f1730f73844173ee73e4a1666e1f02d479/src/main/java/mServer/crawler/sender/MediathekArd.java#L102): Define a constant instead of duplicating this literal "&amp;" 4 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [MediathekArd.java#L122](https://github.com/mediathekview/MServer/blob/a1ecc3f1730f73844173ee73e4a1666e1f02d479/src/main/java/mServer/crawler/sender/MediathekArd.java#L122): Define a constant instead of duplicating this literal "<a href=\"/tv/" 3 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [MediathekArd.java#L124](https://github.com/mediathekview/MServer/blob/a1ecc3f1730f73844173ee73e4a1666e1f02d479/src/main/java/mServer/crawler/sender/MediathekArd.java#L124): Define a constant instead of duplicating this literal "http://www.ardmediathek.de/tv/" 3 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [MediathekArd.java#L220](https://github.com/mediathekview/MServer/blob/a1ecc3f1730f73844173ee73e4a1666e1f02d479/src/main/java/mServer/crawler/sender/MediathekArd.java#L220): Refactor this method to reduce its Cognitive Complexity from 40 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![CRITICAL][CRITICAL] [MediathekArd.java#L390](https://github.com/mediathekview/MServer/blob/a1ecc3f1730f73844173ee73e4a1666e1f02d479/src/main/java/mServer/crawler/sender/MediathekArd.java#L390): Define a constant instead of duplicating this literal "?url=" 6 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
1. ![MAJOR][MAJOR] [MediathekArd.java#L117](https://github.com/mediathekview/MServer/blob/a1ecc3f1730f73844173ee73e4a1666e1f02d479/src/main/java/mServer/crawler/sender/MediathekArd.java#L117): Either remove or fill this block of code. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00108)
1. ![MAJOR][MAJOR] [MediathekArd.java#L205](https://github.com/mediathekview/MServer/blob/a1ecc3f1730f73844173ee73e4a1666e1f02d479/src/main/java/mServer/crawler/sender/MediathekArd.java#L205): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
