### PR TITLE
Fix Längenermittlung

### LINKED ISSUE #189: ZDF-Tivi: Längenerkennung funktioniert nicht korrekt
Übernommen aus Meldung in [MediathekView-Issue](https://github.com/mediathekview/MediathekView/issues/262):

Die Längenerkennung für ZDF-Tivi-Filme funktioniert teilweise nicht korrekt. 
Beispiel für das Thema Heidi: statt ca. 22 Minuten wird 1:44 Minute als Länge angegeben.

### PR DESCRIPTION
**Pull request by pidoubleyou**
ns3:duration nicht mehr verwendet, da dies die Länge des Teasers
beinhaltet. Stattdessen duration oder lengthSec verwendet.

Fixes #189

### CODE REVIEW

File: src/main/java/mServer/crawler/sender/MediathekZdfTivi.java [hunk 1]
```diff
@@ -317,7 +301,39 @@ private void addTivi_(String url) {
...
+                }
+            } catch (NumberFormatException ex) {
+                Log.errorLog(349761012, ex, "Dauer: " + url);
+            }
 
+            return dauer;
+        }
+        
+        // Parst Längenangaben im Format P0Y0M0DT0H22M6.000S
+        private long parseDuration(String duration) throws NumberFormatException {
```
Comment (alex1702) [inline src/main/java/mServer/crawler/sender/MediathekZdfTivi.java]: MINOR Remove the declaration of thrown exception 'java.lang.NumberFormatException' which is a runtime exception. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

File: src/main/java/mServer/crawler/sender/MediathekZdfTivi.java [hunk 2]
```diff
@@ -317,7 +301,39 @@ private void addTivi_(String url) {
...
+            
+            duration = duration.replace("P0Y0M0DT", "");
```
Comment (alex1702) [inline src/main/java/mServer/crawler/sender/MediathekZdfTivi.java]: MINOR Introduce a new variable instead of reusing the parameter "duration". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1226)

**Comment by alex1702** [comment]
SonarQube analysis reported 2 issues
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
